services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - id-network

  app:
    build: .
    container_name: identity-reconcilliation
    image: identity-reconcilliation
    ports:
      - "8080:8080"
    env_file:
    - .env 
    volumes:
      - ./.env:/.env
    depends_on:
      - db
    networks:
      - id-network

networks:
  id-network:
    driver: bridge