name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'

      - name: Verify formatting
        run: test -z "$(gofmt -l .)"

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run unit tests
        run: go test ./... -v

      - name: Build Docker image
        run: docker build -t identity-reconciliation .
